using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Disolve : MonoBehaviour
{
    Material material;

    bool isDisolving = false;
    float fade = 1f;
    void Start()
    {
        material = GetComponent<SpriteRenderer>().material;
    }

   
    void Update()
    {

        if (Input.GetKeyDown(KeyCode.Space))
        {
            isDisolving = true;
        }

        if (isDisolving)
        {
            fade -= Time.deltaTime;
            if (fade <= 0f)
            {
                fade = 0f;
                isDisolving = false;
            }

            material.SetFloat("_Fade", fade);

        }
        
    }
}
